services:
  postgress:
    build:
      context: .
      dockerfile: Dockerfile.postgress
    image: my-postgres-image
    container_name: my-postgres-container-0
    user: root
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: test
    ports:
      - "5433:5432"
    networks:
      - data-qual-private


  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: my-mongo-image
    container_name: my-mongo-container-0
    user: root
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      MONGO_DATABASE: test
    ports:
      - "27018:27017"
    networks:
      - data-qual-private

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-mysql-container-0
    user: root
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    networks:
      - data-qual-private

  connector-server:
    build:
      context: ./generic-connector
    container_name: connector-server
    ports:
      - "5001:5000"
    networks:
      - data-qual-private


    data-ingestion:
      build:
        context: ./data-ingestion
      container_name: data-ingestion-server
      environment:
        GENERIC_CONNECTOR_URL: http://connector-server:5000

        POSTGRES_HOST: my-postgres-container-0
        POSTGRES_PORT: 5432
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DATABASE: test

        MYSQL_HOST: my-mysql-container-0
        MYSQL_PORT: 3306
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: test

        MONGO_HOST: my-mongo-container-0
        MONGO_PORT: 27017
        MONGO_USER: admin
        MONGO_PASSWORD: admin
        MONGO_DATABASE: test
      ports:
        - "5050:5050"
      networks:
        - data-qual-private



networks:
  data-qual-private:
    driver: bridge
