services:
  postgress:
    build:
      context: .
      dockerfile: Dockerfile.postgress
    image: my-postgres-image
    container_name: my-postgres-container-0
    user: root
    env_file:
      - ./envs/.env.postgres
    ports:
      - "5433:5432"
    networks:
      - data-qual-private
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: my-mongo-image
    container_name: my-mongo-container-0
    user: root
    env_file:
      - ./envs/.env.mongo
    ports:
      - "27018:27017"
    networks:
      - data-qual-private
    volumes:
      - mongo_data:/data/db

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-mysql-container-0
    user: root
    env_file:
      - ./envs/.env.mysql
    ports:
      - "3307:3306"
    networks:
      - data-qual-private
    volumes:
      - mysql_data:/var/lib/mysql

  connector-server:
    build:
      context: ./generic-connector
      dockerfile: Dockerfile.generic_connector
    container_name: connector-server
    env_file:
      - ./envs/.env.generic_connector
    ports:
      - "5001:5000"
    networks:
      - data-qual-private
    depends_on:
      - postgress
      - mysql
      - mongo

  data-ingestion:
    build:
      context: ./data-ingestion
      dockerfile: Dockerfile.data_ingestion
    container_name: data-ingestion-server
    env_file:
      - ./envs/.env.data_ingestion
    ports:
      - "5050:5050"
    networks:
      - data-qual-private
    depends_on:
      - connector-server

  qa_postgress:
    build:
      context: .
      dockerfile: Dockerfile.postgress
    image: my-qa-postgres-image
    container_name: my-qa-postgres-container-0
    user: root
    env_file:
      - ./envs/.env.qa_postgres
    ports:
      - "5434:5433"
    networks:
      - data-qual-private
    volumes:
      - qa_postgres_data:/var/lib/postgresql/data

  qa-service:
    build:
      context: ./qa-service
      dockerfile: Dockerfile.qa_service
    container_name: qa-server
    env_file:
      - ./envs/.env.qa_service
    ports:
      - "9090:9090"
    networks:
      - data-qual-private
    depends_on:
      - qa_postgress
      - connector-server

networks:
  data-qual-private:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
  qa_postgres_data:
